# Site settings
title: Blog
email: contato@deoliveiralucas.net
description: Blog sobre qualquer coisa sobre programa√ßao
baseurl: "http://deoliveiralucas.github.io"
url: "http://deoliveiralucas.github.io"

author:
  name     : 'Fernando Moreira'
  email    : hi@nandomoreira.me
  url      : http://nandomoreira.me
  facebook : http://facebook.com/fernando.dev
  twitter  : http://twitter.com/nandomoreirame

github: https://github.com/nandomoreirame/zetsu
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
